apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
data:
  repositories: |
    - url: gitlab_repository_to_clone
      type: git
      passwordSecret:
        key: password
        name: repo-secret
      usernameSecret:
        key: username
        name: repo-secret
