---
- hosts: "k8s-master"
  become: false
  tags: import-repository
  roles:
    - setup_gitlab_ssh_key
    - setup_gitlab_repository

- hosts: "k8s-master"
  become: false
  tags: configure-argocd-repository
  roles:
    - configure_argocd_repository
